package com.medtrack.util;

import com.itextpdf.io.source.ByteArrayOutputStream;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.medtrack.model.EquipmentOrder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;

@Component
public class PurchaseOrderPdf {
    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public byte[] generate(EquipmentOrder order) {
        if (order == null) {
            throw new IllegalArgumentException("Equipment order is required to generate a purchase order PDF");
        }

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(outputStream);
        PdfDocument pdfDocument = new PdfDocument(writer);

        try (Document document = new Document(pdfDocument)) {
            document.add(new Paragraph("MEDTRACK PURCHASE ORDER")
                    .setBold()
                    .setFontSize(18)
                    .setTextAlignment(TextAlignment.CENTER));
            document.add(new Paragraph("Purchase Order / Invoice Document")
                    .setFontSize(11)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(18));

            Table table = new Table(UnitValue.createPercentArray(new float[]{35, 65}))
                    .useAllAvailableWidth();
            addRow(table, "Order Code", order.getOrderCode());
            addRow(table, "Hospital", order.getHospital());
            addRow(table, "Created By", order.getCreatedBy());
            addRow(table, "Equipment ID", order.getEquipmentId());
            addRow(table, "Equipment Name", order.getEquipmentName());
            addRow(table, "Quantity", order.getQuantity());
            addRow(table, "Unit Cost", formatMoney(order.getUnitCost()));
            addRow(table, "Total Cost", formatMoney(order.getTotalCost()));
            addRow(table, "Approval Status", order.getApprovalStatus());
            addRow(table, "Order Status", order.getStatus());
            addRow(table, "Order Date", formatOrderDate(order));
            addRow(table, "Notes", order.getNotes());
            document.add(table);

            document.add(new Paragraph("Generated by MedTrack Equipment Procurement & Order Service")
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(24));
        }

        return outputStream.toByteArray();
    }

    private void addRow(Table table, String label, Object value) {
        table.addCell(new Cell()
                .add(new Paragraph(label).setBold())
                .setBackgroundColor(ColorConstants.LIGHT_GRAY)
                .setBorder(new SolidBorder(ColorConstants.GRAY, 0.5f)));
        table.addCell(new Cell()
                .add(new Paragraph(valueOrDefault(value)))
                .setBorder(new SolidBorder(ColorConstants.GRAY, 0.5f)));
    }

    private String formatOrderDate(EquipmentOrder order) {
        return order.getOrderDate() == null ? "N/A" : DATE_TIME_FORMATTER.format(order.getOrderDate());
    }

    private String formatMoney(BigDecimal value) {
        return value == null ? "N/A" : value.toPlainString();
    }

    private String valueOrDefault(Object value) {
        return value == null ? "N/A" : value.toString();
    }
}
