package com.medtrack.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "maintenance_tasks")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MaintenanceTask {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Generated by the service so callers cannot choose or reuse task identifiers.
    @Column(nullable = false, unique = true, updatable = false)
    private String taskCode;

    @NotBlank(message = "Equipment ID is required")
    private String equipmentId;
    private String equipment;

    // Every migrated and newly-created task must reference a real equipment record.
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "equipment_record_id", nullable = false)
    @JsonIgnore
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Equipment equipmentRecord;

    private String hospital;

    // Stable ownership key used by the service to isolate one hospital's tasks from another.
    @Column(name = "hospital_id", nullable = false)
    private Long hospitalId;

    @NotBlank(message = "Maintenance type is required")
    private String maintenanceType;

    @NotNull(message = "Deadline is required")
    private LocalDate deadline;
    private String assignedTechnician;
    private String description;
    @NotBlank(message = "Priority is required")
    @Pattern(regexp = "Normal|High|Critical", message = "Priority must be Normal, High, or Critical")
    private String priority;
    private String image;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    @NotNull(message = "Status is required")
    private MaintenanceStatus status = MaintenanceStatus.SCHEDULED;

    @Column(columnDefinition = "TEXT")
    private String notes;

    @PositiveOrZero(message = "Hours worked cannot be negative")
    private Double hoursWorked;

    private String partsUsed;

    @Column(columnDefinition = "TEXT")
    private String signature;

    // Set by the service on the first valid transition to COMPLETED.
    private LocalDateTime completedAt;

    @PositiveOrZero(message = "Recurrence period cannot be negative")
    private Integer recurrencePeriodDays;

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
