package com.medtrack.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.medtrack.auth.model.User;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDate;
import java.time.LocalDateTime;

import static com.medtrack.validation.MaintenanceValidationLimits.NOTES_MAX_LENGTH;
import static com.medtrack.validation.MaintenanceValidationLimits.SHORT_TEXT_MAX_LENGTH;
import static com.medtrack.validation.MaintenanceValidationLimits.SIGNATURE_MAX_LENGTH;

@Entity
@Table(name = "maintenance_tasks")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MaintenanceTask {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Generated by the service so callers cannot choose or reuse task identifiers.
    @Column(nullable = false, unique = true, updatable = false)
    private String taskCode;

    @NotBlank(message = "Equipment ID is required")
    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Equipment ID must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String equipmentId;
    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Equipment name must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String equipment;

    // Every migrated and newly-created task must reference a real equipment record.
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "equipment_record_id", nullable = false)
    @JsonIgnore
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Equipment equipmentRecord;

    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Hospital name must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String hospital;

    // Stable ownership key used by the service to isolate one hospital's tasks from another.
    @Column(name = "hospital_id", nullable = false)
    private Long hospitalId;

    @NotBlank(message = "Maintenance type is required")
    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Maintenance type must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String maintenanceType;

    @NotNull(message = "Deadline is required")
    private LocalDate deadline;
    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Assigned technician must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String assignedTechnician;

    // Stable authorization identity. The email field above remains the API-facing value.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_technician_record_id")
    @JsonIgnore
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private User assignedTechnicianRecord;

    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Description must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String description;
    @NotBlank(message = "Priority is required")
    @Pattern(regexp = "Normal|High|Critical", message = "Priority must be Normal, High, or Critical")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String priority;
    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Image reference must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String image;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    @NotNull(message = "Status is required")
    private MaintenanceStatus status = MaintenanceStatus.SCHEDULED;

    @Column(columnDefinition = "TEXT")
    @Size(max = NOTES_MAX_LENGTH, message = "Notes must not exceed 16000 characters")
    private String notes;

    @PositiveOrZero(message = "Hours worked cannot be negative")
    private Double hoursWorked;

    @Size(max = SHORT_TEXT_MAX_LENGTH, message = "Parts used must not exceed 255 characters")
    @Column(length = SHORT_TEXT_MAX_LENGTH)
    private String partsUsed;

    @Column(columnDefinition = "TEXT")
    @Size(max = SIGNATURE_MAX_LENGTH, message = "Signature must not exceed 60000 characters")
    private String signature;

    // Set by the service on the first valid transition to COMPLETED.
    private LocalDateTime completedAt;

    @PositiveOrZero(message = "Recurrence period cannot be negative")
    private Integer recurrencePeriodDays;

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
